PREFIX seas: <https://w3id.org/seas/>
PREFIX sosa: <http://www.w3c.org/ns/sosa/>
PREFIX ssn: <http://www.w3c.org/ns/ssn/>

SELECT ?actuator WHERE {
  SERVICE <http://localhost:8001/data_catalouge.ttl> {
    ?room a seas:Room , sosa:FeatureOfInterest ;
      ssn:hasProperty ?temperature , ?occupancy ;
      seas:onFloor ?floor .

    ?temperature a sosa:ObservableProperty , seas:TemperatureProperty .
    ?occupancy a sosa:ObservableProperty , seas:OccupancyProperty .

    ?temp_obs a sosa:Observation ;
      sosa:hasFeatureOfInterest ?room ;
      sosa:observedProperty ?temperature ;
      sosa:hasSimpleResult ?temp_value .

    ?occ_obs a sosa:Observation ;
      sosa:hasFeatureOfInterest ?room ;
      sosa:observedProperty ?occupancy ;
      sosa:hasSimpleResult ?occ_value .

    ?actuator sosa:actsOnProperty ?temperature .

      FILTER( ?floor = 2 && ?temp_value > 14m && ?occ_value = 0 )
    }
}
